#if !COMPILER_UDONSHARP
using System.Collections;
using System.Collections.Generic;
using System.Text;

namespace JLChnToZ.Regex2Pattern {
    /// <summary>
    /// Interface for generating all strings matching a regular expression pattern.
    /// </summary>
    public interface IGenerator : IEnumerable<string> {
        /// <summary>
        /// Returns an enumerator that iterates through all strings generated by this <see cref="IGenerator"/>.
        /// </summary>
        /// <returns>An enumerator that can be used to iterate through all generated strings.</returns>
        /// <remarks>
        /// This is a compiler-friendly method that allows the use of <see cref="foreach"/> loops and LINQ queries
        /// efficiently without boxing enumerators.
        /// The returned <see cref="Enumerator"/> struct implements the standard <see cref="IEnumerator{T}"/> interface.
        /// </remarks>
        public new Enumerator GetEnumerator();
    }

    /// <summary>
    /// Enumerator for iterating through all strings generated by an <see cref="IGenerator"/>.
    /// </summary>
    /// <remarks>
    /// This struct is returned by the <see cref="IGenerator.GetEnumerator"/> method and implements the standard <see cref="IEnumerator{T}"/>
    /// interface for use in foreach loops and LINQ queries.
    /// </remarks>
    public struct Enumerator : IEnumerator<string> {
        readonly BaseNode node;
        readonly StringBuilder sb;
        bool hasNext;

        public readonly string Current => sb.ToString();

        readonly object IEnumerator.Current => sb.ToString();

        internal Enumerator(BaseNode node) {
            this.node = node;
            sb = new StringBuilder();
            hasNext = true;
        }

        public bool MoveNext() {
            if (!hasNext) return false;
            sb.Clear();
            node.Write(sb);
            hasNext = node.Next();
            return true;
        }

        public void Reset() {
            node.Reset();
            sb.Clear();
            hasNext = true;
        }

        public readonly void Dispose() { }
    }
}
#endif
